name: Build and Push to ECR

on:
  push:
    branches: [main]

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.AWS_REGION }}

      - name: Login to Amazon ECR
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v1

      - name: Build Docker image
        run: |
          IMAGE_TAG=${{ github.sha }}
          docker build -t ${{ secrets.ECR_REGISTRY }}/${{ secrets.ECR_REPOSITORY }}:$IMAGE_TAG -f app/Dockerfile app

      - name: Push Docker image to ECR
        run: |
          IMAGE_TAG=${{ github.sha }}
          docker push ${{ secrets.ECR_REGISTRY }}/${{ secrets.ECR_REPOSITORY }}:$IMAGE_TAG
      
      - name: Commit updated image tag to Terraform tfvars
        run: |
          IMAGE_TAG=${{ github.sha }}
          echo "{\"docker_image_tag\": \"${IMAGE_TAG}\"}" > terraform/dev/docker.auto.tfvars.json
          git config user.name "aalindsingh"
          git config user.email "aalindsingh@gmail.com"
          git add terraform/dev/docker.auto.tfvars.json
          git commit -m "Update image tag to ${IMAGE_TAG}" || echo "No changes to commit"
          git push    
